import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';

const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'ledger-m1-'));
const port=21000+crypto.randomInt(10000), base=`http://127.0.0.1:${port}`;
const env={...process.env,PORT:String(port),LEDGER_PASSWORD:'test-password',LEDGER_SESSION_SECRET:'s'.repeat(40),LEDGER_KEY_SECRET:'k'.repeat(40)};
const child=spawn(process.execPath,[path.join(import.meta.dirname,'server.mjs')],{cwd,env,stdio:'ignore'});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function request(route,body,token,method='POST'){let res=await fetch(base+route,{method,headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return [res,await res.json()]}
try {
 let ready=false;for(let n=0;n<50;n++){try{await fetch(base);ready=true;break}catch{await wait(100)}}assert(ready,'server starts');const page=await (await fetch(base)).text(),client=page.slice(page.lastIndexOf('<script>')+8,page.lastIndexOf('</script>'));assert.doesNotThrow(()=>new Function(client),'embedded browser JavaScript parses');const app={};const rendered=new Function('localStorage','document',client+";state={accounts:[],providers:[],imports:[],transactions:[],matches:[],candidates:[],finance:{summary:{currencies:{}},accountBalances:{}}};render();return document.getElementById('app').innerHTML")({ledgerSession:''},{getElementById:()=>app});assert(rendered.includes('完整账单 CSV 复核')&&rendered.includes('备份与恢复'),'authenticated dashboard renders all sections');
 let [r,d]=await request('/api/state',undefined);assert.equal(r.status,401,'API protected');
 [r,d]=await request('/api/login',{password:'test-password'});assert.equal(r.status,200);const token=d.token,today=new Date().toISOString().slice(0,10),yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);
 [r,d]=await request('/api/accounts',{name:'银行卡',type:'银行卡',openingBalance:'1000.00',asOf:yesterday},token);assert.equal(r.status,201);[r,d]=await request('/api/state',undefined,token,'GET');const accountId=d.accounts[0].id;
 const data='data:image/png;base64,aGVsbG8=';
 [r,d]=await request('/api/import',{imageData:data,mime:'image/png',source:'测试',anchor:today},token);assert.equal(r.status,200);const importId=d.id;
 [r,d]=await request('/api/import',{imageData:data,mime:'image/png',source:'测试'},token);assert.equal(d.duplicate,true,'identical upload is idempotent');
 [r,d]=await request(`/api/import/${importId}/confirm`,{records:[{merchant:'零食很忙',date:today,amount:'1.10',type:'expense',accountId}]},token);assert.equal(d.saved,1);
 [r,d]=await request('/api/state',undefined,token,'GET');assert.equal(d.transactions.length,1);assert.equal(d.transactions[0].amountCents,110);assert.equal(d.finance.accountBalances[accountId],99890,'asset expense reduces balance in integer cents');
 const second='data:image/png;base64,aGVsbG82';[r,d]=await request('/api/import',{imageData:second,mime:'image/png',source:'银行',anchor:today},token);const secondId=d.id;[r,d]=await request(`/api/import/${secondId}/confirm`,{records:[{merchant:'零食很忙',date:today,amount:'1.10',type:'expense'}]},token);assert.equal(d.saved,1);[r,d]=await request('/api/state',undefined,token,'GET');assert.equal(d.candidates.length,1,'cross-source pair is suggested');const pair=d.candidates[0];[r,d]=await request('/api/matches',{a:pair.a,b:pair.b,kind:'same'},token);assert.equal(r.status,200);[r,d]=await request('/api/state',undefined,token,'GET');assert.equal(d.finance.summary.expenseCents,110,'linked duplicate counted once');assert.equal(d.finance.accountBalances[accountId],99890,'dedup does not double count account movement');
  [r,d]=await request('/api/accounts',{name:'美元卡',type:'银行卡',currency:'USD',openingBalance:'50.00',asOf:yesterday},token);[r,d]=await request('/api/state',undefined,token,'GET');const usdAccount=d.accounts.find(x=>x.currency==='USD').id;[r,d]=await request('/api/import',{imageData:'data:image/png;base64,dXNk',mime:'image/png',source:'USD测试',currency:'USD',anchor:today},token);const usdImport=d.id;[r,d]=await request(`/api/import/${usdImport}/confirm`,{records:[{merchant:'美元消费',date:today,amount:'1.00',type:'expense',currency:'USD',accountId:usdAccount}]},token);assert.equal(d.saved,1);[r,d]=await request('/api/state',undefined,token,'GET');assert.equal(d.finance.accountBalances[usdAccount],4900,'USD account keeps cents and updates independently');assert.equal(d.finance.summary.currencies.USD.monthExpenseCents,100);
 const csv=`date,merchant,amount\n${today},零食很忙,1.10\n2025-01-02,咖啡店,2.35\n`;[r,d]=await request('/api/statement/preview',{csv,source:'银行完整账单',accountId,map:{date:0,merchant:1,amount:2}},token);assert.equal(r.status,200);assert.equal(d.report.matched.length,1);assert.equal(d.report.missing.length,1);[r,d]=await request('/api/statement/import',{id:d.report.id},token);assert.equal(d.imported,1);[r,d]=await request('/api/statement/preview',{csv,source:'银行完整账单',accountId,map:{date:0,merchant:1,amount:2}},token);assert.equal(d.duplicate,true,'CSV file import idempotent');
 const refundImage='data:image/png;base64,cmVmdW5k';[r,d]=await request('/api/import',{imageData:refundImage,mime:'image/png',source:'支付宝退款',anchor:today},token);const refundImport=d.id;[r,d]=await request(`/api/import/${refundImport}/confirm`,{records:[{merchant:'零食很忙',date:today,amount:'0.50',type:'refund'}]},token);[r,d]=await request('/api/state',undefined,token,'GET');const refundId=d.transactions.find(x=>x.type==='refund').id,expenseId=d.transactions.find(x=>x.type==='expense').id;[r,d]=await request('/api/matches',{a:refundId,b:expenseId,kind:'refund'},token);assert.equal(r.status,200,'partial refund linked');
  [r,d]=await request('/api/backup',undefined,token,'GET');const backup=d;assert.equal(backup.version,1);[r,d]=await request('/api/restore',{backup:{...backup,version:999}},token);assert.equal(r.status,400,'invalid backup rejected');[r,d]=await request('/api/restore',{backup},token);assert.equal(r.status,200,'valid backup restores');[r,d]=await request('/api/state',undefined,token,'GET');assert.equal(d.transactions.length,5,'restore kept verified ledger data');
 [r,d]=await request(`/api/import/${importId}/confirm`,{records:[{amount:'1.00'}]},token);assert.equal(r.status,400,'confirmed import cannot be duplicated');
 [r,d]=await request('/api/import/'+importId+'/confirm',{records:[{merchant:'x',amount:'1.001'}]},token);assert.equal(r.status,400,'fractional precision validated');
 [r,d]=await request('/api/providers',{name:'bad',baseUrl:'http://127.0.0.1',model:'x'},token);assert.equal(r.status,400,'non-HTTPS rejected');
 await import('./ledger.test.mjs');console.log('Ledger integration tests passed');
} finally {child.kill();await wait(100);fs.rmSync(cwd,{recursive:true,force:true})}
